Feature/lesson 12
tahyhax/intern-js-test pull request #10
Opened 2022-01-26 21:39 UTC by tahyhax

2022-01-27 14:12 UTC, kovalenk requested changes
- таски в календаре выводятся по дате завершения, а должны по дате создания
- поиск по датам проверять строго (с учётом выбранную дату)
- что-то не то с модалкой создания таски ( редактирование нормальное )

2022-01-27 14:12 UTC, kovalenk commented on src/views/Tasks.vue
> +    // поиидее должно вынетстить useModal
Можешь вынести, лишним не будет

2022-01-28 21:47 UTC, tahyhax commented on src/views/Tasks.vue
> +    // поиидее должно вынетстить useModal
сделать composition api для  модального окна не успеваю. Постараюсь сделать с 14 заданием.

2022-02-03 13:35 UTC, kovalenk approved these changes
👍

2022-02-03 13:35 UTC, merged