Feature/lesson 9 kanban board
tahyhax/intern-js-test pull request #6
Opened 2021-12-08 20:17 UTC by tahyhax

2021-12-13 22:05 UTC, maryiv requested changes

2021-12-13 22:05 UTC, maryiv commented on src/types/task.ts
> +export const enum ETaskStatus {
Можем использовать `export enum`
При том, что у нас всё зафиксировано в пакетном менеджере, то проблема для нас не очень и актуальна, просто для ознакомления https://ncjamieson.com/dont-export-const-enums/

2021-12-13 22:05 UTC, maryiv commented on src/components/Kanban/KanbanColumn.vue
> +    cursor: pointer;
Пока у нас нет возможности перетаскивать, лучше не использовать данный курсор
Он обычно используется, если над элементом можно провести действия или элемент кликабельный

2021-12-13 22:05 UTC, maryiv commented on src/views/Kanban.vue
> +        tasks: [
Тоже вариант)
Но нам нужно вести работу с массивом задач, в котором статусы вперемешку.
Мы можем подвести тот массив к виду, который есть сейчас, но на данный момент этот шаг пропущен.
В дальнейшем мы будем использовать Vuex и данные на странице задач и доски будут синхронизироваться

2021-12-17 12:26 UTC, maryiv approved these changes

2021-12-17 12:26 UTC, maryiv commented on src/router/index.ts
> +    component: import('../views/Tasks.vue')
Тут желательно прописывать динамический (lazy) импорт
Если без него, то страничку обычно оформляют как обычный импорт

2021-12-17 12:26 UTC, merged

2022-01-06 19:09 UTC, tahyhax commented on src/router/index.ts
> +    component: import('../views/Tasks.vue')
fixed  in lesson 10